os:
- linux
dist: trusty
language: generic
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive-2016'
      - sourceline: 'ppa:hvr/ghc'
    packages:
    - texlive
    - gv
    - texlive-fonts-recommended
    - build-essential
    - cabal-install-2.0
    - ghc-8.2.2

install:
- export PATH=$PATH:~/.cabal/bin:/opt/ghc/bin
- cabal update
- cabal install -j2 --user pandoc pandoc-crossref

script:
- make clean all

before_cache:
  - rm -f $HOME/.cabal/logs/*.log
