os:
- linux
dist: trusty
language: generic
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive-2016'
      - sourceline: 'ppa:hvr/ghc'
    packages:
    - texlive
    - texlive-lang-cjk
    - texlive-lang-japanese
    - dvipsk-ja
    - xdvik-ja
    - gv
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - ruby-dev
    - build-essential
    - cabal-install-2.0

install:
- export PATH=$PATH:~/.cabal/bin:/opt/ghc/bin
- cabal update
- cabal install -j2 --user pandoc pandoc-crossref

script:
- make clean all

before_cache:
  - cabal list --installed --simple-output
  - rm -f $HOME/.cabal/logs/*.log
